name: flutter_restate_app
description: "A Real State app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  flutter_native_splash: ^2.4.5
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.4
  fade_shimmer: ^2.4.0

  # STATE MANAGEMENT
  provider: ^6.1.2

  # AUTHENTICATION
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.1.4
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3



flutter:
  uses-material-design: true

  # LOCAL ASSETS
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # LOCAL FONTS
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800

#  # flutter launcher icons
#  flutter_launcher_icons:
#    android: true
#    ios: true
#    image_path: "assets/images/favicon.png"
#    adaptive_icon_background: "#ffffff"
#    adaptive_icon_foreground: "assets/images/favicon.png"
#    remove_alpha_ios: true




